ProfileMenu
Newbies-Workplace/jeteo pull request #39
Opened 2023-08-13 19:27 UTC by HIYJOKOU

2023-08-13 19:28 UTC, HIYJOKOU commented on apps/web/src/components/molecules/userMenu/UserMenu.tsx
> +                <Text variant="headS" bold={true} className={styles.text}>{user?.nick} {user?.avatar}</Text>
usunalem juz {user?.avatar}

2023-08-15 11:32 UTC, JUtupe requested changes

2023-08-15 11:32 UTC, JUtupe commented on apps/web/src/assets/default-profile-picture.svg
jak dodajesz ten profile to ten poprzedni można usunąć, dodatkowo imo lepiej żeby to było w formacie kwadratu, jeśli kiedyś będziemy chcieli zmienić border radius to będzie to normalniej wyglądać

2023-08-15 11:32 UTC, JUtupe commented on apps/web/src/components/molecules/userMenu/UserMenu.module.scss
> +    // margin-bottom: 6.5px;
komentarz

2023-08-15 11:32 UTC, JUtupe commented on apps/web/src/components/organisms/profileMenu/ProfileMenu.tsx
> +import GuestMenu from "@/components/molecules/guestMenu/GuestMenu";
zmieniłbym paczkę tych menu na `/organisms/profileMenu/menus`, i tak te komponenty nie będą raczej używane poza ProfileMenu

2023-08-15 12:22 UTC, JUtupe approved these changes

2023-08-15 12:27 UTC, merged

2023-08-15 12:29 UTC, JUtupe approved these changes