Fix/speaker card
Newbies-Workplace/jeteo pull request #82
Opened 2023-11-29 09:33 UTC by Filszu

2023-11-29 09:48 UTC, JUtupe requested changes

2023-11-29 09:48 UTC, JUtupe commented on apps/web/src/app/events/[slug]/page.tsx
> +              {/* TODO: extract to separate component */}
to do osobnego zadania

2023-11-29 09:48 UTC, JUtupe commented on apps/web/src/components/atoms/iconButton/IconButton.tsx
> +  // btnSize=40,
```suggestion
```

2023-11-29 09:48 UTC, JUtupe commented on apps/web/src/components/atoms/iconButton/IconButton.tsx
> +        height={size==="medium"?24:size==="small"?18:10}
size można wyciągnąć do zmiennej wyżej, można też się pozbyć defaulowej wartości 10, która nigdy nie wystąpi

2023-11-29 09:48 UTC, JUtupe commented on apps/web/src/components/atoms/iconButton/IconButton.tsx
> +  btnSize?: number;
```suggestion
```

2023-11-29 09:48 UTC, JUtupe commented on apps/web/src/components/molecules/speakerCard/SpeakerCard.module.scss
> +// box-shadow: 4px 4px 8px 0px rgba(66, 68, 90, 1);
usuń pls komentarze w tym pliku

2023-11-29 09:48 UTC, JUtupe commented on apps/web/src/components/molecules/speakerCard/SpeakerCard.module.scss
> +  padding: 12px;
```suggestion
  padding: 8px;
```

2023-11-30 11:54 UTC, Filszu commented on apps/web/src/components/atoms/iconButton/IconButton.tsx
> +  // btnSize=40,
//

2023-11-30 13:16 UTC, merged